### ISSUE TITLE
`tec.TECBase` can be instantiated with non-electrode data for "emitter" arg

### ISSUE THREAD

**Issue by jrsmith3** [jrsmith3/tec#76]
`tec.TECBase` objects should only be able to be instantiated with data of type coming from the `tec.electrode` submodule (currently includes `tec.electrode.Metal`, `tec.electrode.SC`). This requirement is implied in the class's docstring, but it could be made much more clear.

This bug was first noticed at commit 6914b6bf23aa820778f83f71c93a6862b619929c by writing the following tests: 

* `test/test_TECBase.py:InstantiationInputWrongType.test_emitter_non_numeric`
* `test/test_TECBase.py:InstantiationInputWrongType.test_collector_non_numeric`

Failure message
===============
```
.......................................FF
======================================================================
FAIL: collector nonelectrode -> TECBase init raises TypeError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jrsmith3/Documents/work/tec/test/test_TECBase.py", line 48, in test_collector_non_numeric
    self.assertRaises(TypeError, TECBase, self.em, non_electrode)
AssertionError: TypeError not raised

======================================================================
FAIL: emitter nonelectrode -> TECBase init raises TypeError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jrsmith3/Documents/work/tec/test/test_TECBase.py", line 41, in test_emitter_non_numeric
    self.assertRaises(TypeError, TECBase, non_electrode, self.co)
AssertionError: TypeError not raised

----------------------------------------------------------------------
Ran 41 tests in 0.140s

FAILED (failures=2)
```

Solution
========
Both `emitter` and `collector` attributes will likely have to be implemented as properties, descriptors are probably overkill at this point. ([python docs](https://docs.python.org/2/howto/descriptor.html), [Chris Beaumont's tutorial](http://nbviewer.ipython.org/urls/gist.github.com/ChrisBeaumont/5758381/raw/descriptor_writeup.ipynb)). I don't expect the python property aspect of this fix to be too difficult, but I'm not sure how to test that an object comes from the `tec.electrode` namespace. I'll probably have to check that it inherits from `tec.electrode.Metal`.

Additionally, I will update docstring to note that this class will raise a `TypeError` if either the "emitter" or "collector" arg are non-electrode type.

Additional information
=====================
I have a test class `test/test_TECBase:SetAttribsWrongType`. It does not contain tests yet, but I'm pretty sure that if I fix this bug I will preempt bugs discovered with these kinds of tests.

**Comment by jrsmith3** [comment]
SO has a [post](http://stackoverflow.com/questions/2611892/get-python-class-parents) on how to find parent classes. Perhaps `inspect.getmro` is a clue to finding out if an object comes from `tec.electrode`. The following seems to work

```python
>>> import inspect
>>> from tec.electrode import Metal
>>> em = Metal(temp=1000., barrier=2., richardson=10.)
>>> # I don't have to use the whole namespace below because I imported `Metal` directly.
>>> Metal in inspect.getmro(em.__class__)
True
```

I think the above means that somewhere in the inheritance chain of the `em` object is a `tec.electrode.Metal`.
